// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadFile returns the embedded CollectionSpec for file.
func loadFile() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FileBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load file: %w", err)
	}

	return spec, err
}

// loadFileObjects loads file and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*fileObjects
//	*filePrograms
//	*fileMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFileObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFile()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// fileSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileSpecs struct {
	fileProgramSpecs
	fileMapSpecs
	fileVariableSpecs
}

// fileProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileProgramSpecs struct {
	TracepointSyscallsSysEnterOpenat *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_openat"`
}

// fileMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileMapSpecs struct {
}

// fileVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileVariableSpecs struct {
	PidTarget *ebpf.VariableSpec `ebpf:"pid_target"`
}

// fileObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileObjects struct {
	filePrograms
	fileMaps
	fileVariables
}

func (o *fileObjects) Close() error {
	return _FileClose(
		&o.filePrograms,
		&o.fileMaps,
	)
}

// fileMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileMaps struct {
}

func (m *fileMaps) Close() error {
	return _FileClose()
}

// fileVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileVariables struct {
	PidTarget *ebpf.Variable `ebpf:"pid_target"`
}

// filePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type filePrograms struct {
	TracepointSyscallsSysEnterOpenat *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_openat"`
}

func (p *filePrograms) Close() error {
	return _FileClose(
		p.TracepointSyscallsSysEnterOpenat,
	)
}

func _FileClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed file_bpfel.o
var _FileBytes []byte
