//go:build linux

// main.go — EDR agent userspace component
// Reads events from eBPF kernel programs via ring buffer and perf buffer
// Applies detection rules and prints alerts

package main

import (
	"bytes"
	"encoding/binary" // standard Go library — parse raw bytes into structs
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/cilium/ebpf/link"    // attach eBPF programs to kernel hooks
	"github.com/cilium/ebpf/perf"    // read from BPF_MAP_TYPE_PERF_EVENT_ARRAY (old pattern)
	"github.com/cilium/ebpf/ringbuf" // read from BPF_MAP_TYPE_RINGBUF (new pattern)
	"github.com/cilium/ebpf/rlimit"  // remove memory lock limit for eBPF
)

// ─────────────────────────────────────────────
// Constants — must match values in .h files
// ─────────────────────────────────────────────

const TaskCommLen = 128 // must match #define TASK_COMM_LEN 128 in execsnoop.h

// ─────────────────────────────────────────────
// Event structs — must EXACTLY match C structs in .h files
// Field order, type, and size must be identical
// Go reads raw bytes from kernel and maps them to these structs
// Uppercase fields = exported (required for binary.Read to access them)
// ─────────────────────────────────────────────

// ProcessEvent matches execsnoop.h struct event
// Captures: which process was executed, by whom, and from which container
// Field order + types must EXACTLY match C struct layout (no padding gaps)
type ProcessEvent struct {
	Pid     int32             // process ID (from kernel tgid)
	Ppid    int32             // parent process ID (who spawned this)
	Uid     int32             // user ID (0=root, 1000=your user)
	MntNsId uint32            // mount namespace ID — which container this belongs to
	Comm    [TaskCommLen]byte // binary path e.g. /usr/bin/curl (128 bytes)
}

// ExitEvent matches exitsnoop.h struct event
// Captures: which process exited, how long it ran, exit code
// Field order MUST match C struct exactly — binary.Read maps raw bytes directly
// sizeof(C struct) = 8+4+4+4+4+128 = 152 bytes, no implicit padding
type ExitEvent struct {
	DurationNs uint64            // offset 0  — duration in nanoseconds
	Pid        uint32            // offset 8  — process ID
	Ppid       uint32            // offset 12 — parent process ID
	ExitCode   uint32            // offset 16 — exit code (0=normal)
	Pad        uint32            // offset 20 — matches explicit pad in C struct
	Comm       [TaskCommLen]byte // offset 24 — process name
}

// ─────────────────────────────────────────────
// Main entry point
// ─────────────────────────────────────────────

func main() {
	// Step 1: Remove memory lock limit
	// Linux limits how much memory a process can lock in RAM
	// eBPF maps/programs must be locked (can't swap to disk)
	// Old kernels had ~64KB limit — too small for eBPF
	// RemoveMemlock() removes this limit entirely
	// Safe to call even on kernel 5.11+ where limit is already removed
	if err := rlimit.RemoveMemlock(); err != nil {
		log.Fatal(err)
	}

	// Step 2: Initialize alert handler
	alertHandler, err := NewAlertHandler("alerts/alert.log")
	if err != nil {
		log.Fatalf("opening alert log: %v", err)
	}
	defer alertHandler.Close()

	// Step 2b: Start container namespace resolver
	// Scans /proc/*/ns/mnt to build mnt_ns_id → container_name map
	// Refreshes every 30s to catch new/stopped containers
	StartContainerResolver()

	// Step 3: Load eBPF objects into kernel
	// processObjects — auto-generated by bpf2go in process_bpfel.go
	// Contains: processPrograms (eBPF programs) + processMaps (eBPF maps)
	// loadProcessObjects — auto-generated function, loads compiled .o bytecode into kernel
	// &objs — pass pointer so function can fill the struct
	// nil — use default loading options
	processObjs := processObjects{}
	if err := loadProcessObjects(&processObjs, nil); err != nil {
		// log.Fatalf = log + os.Exit(1) — unrecoverable error, exit immediately
		log.Fatalf("loading process objects: %v", err)
	}
	// defer = run when main() exits, no matter how (normal or panic)
	// Close() unloads eBPF programs and maps from kernel — cleanup
	defer processObjs.Close()

	// exitObjs — auto-generated by bpf2go in exit_bpfel.go
	exitObjs := exitObjects{}
	if err := loadExitObjects(&exitObjs, nil); err != nil {
		log.Fatalf("loading exit objects: %v", err)
	}
	defer exitObjs.Close()

	// Step 3: Attach eBPF programs to kernel hooks
	// link.Tracepoint — from "github.com/cilium/ebpf/link"
	// Args: subsystem, event name, eBPF program, options
	// processObjs.TracepointSyscallsSysEnterExecve — auto-generated field name
	// from process_bpfel.go, maps to SEC("tracepoint/syscalls/sys_enter_execve")
	processTp, err := link.Tracepoint(
		"syscalls",           // kernel subsystem
		"sys_enter_execve",   // tracepoint event name
		processObjs.TracepointSyscallsSysEnterExecve, // eBPF program to attach
		nil,                  // options
	)
	if err != nil {
		log.Fatalf("attaching process tracepoint: %v", err)
	}
	// defer tp.Close() — detaches eBPF from kernel hook when program exits
	// Without this: hook stays attached, events fire but nobody reads them
	defer processTp.Close()

	// Attach exitsnoop — uses sched tracepoint not syscalls
	exitTp, err := link.Tracepoint(
		"sched",
		"sched_process_exit",
		exitObjs.HandleExit,
		nil,
	)
	if err != nil {
		log.Fatalf("attaching exit tracepoint: %v", err)
	}
	defer exitTp.Close()

	// Step 4: Open readers for each eBPF map
	// execsnoop uses PERF_EVENT_ARRAY (old pattern) → perf.NewReader
	// exitsnoop uses RINGBUF (new pattern) → ringbuf.NewReader
	// os.Getpagesize() = 4096 bytes per CPU for perf buffer size
	processRd, err := perf.NewReader(processObjs.Events, os.Getpagesize())
	if err != nil {
		log.Fatalf("opening process perf reader: %v", err)
	}
	defer processRd.Close()

	// ringbuf.NewReader — from "github.com/cilium/ebpf/ringbuf"
	// exitsnoop's map is named "rb" in C → becomes Rb in Go (auto-generated)
	exitRd, err := ringbuf.NewReader(exitObjs.Rb)
	if err != nil {
		log.Fatalf("opening exit ringbuf reader: %v", err)
	}
	defer exitRd.Close()

	log.Println("EDR Monitor started — watching process execution and exits")
	log.Println("Press Ctrl+C to stop")

	// Step 5: Handle Ctrl+C gracefully
	// make(chan os.Signal, 1) — create buffered channel for OS signals
	// signal.Notify — register which signals to catch
	// syscall.SIGINT = Ctrl+C, syscall.SIGTERM = kill command
	sig := make(chan os.Signal, 1)
	signal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)

	// Step 6: Start goroutines to read events
	// go func() — start concurrent goroutine (lightweight thread in Go)
	// Each reader runs in its own goroutine so they don't block each other
	// All goroutines run concurrently — Go scheduler handles it

	// Goroutine 1: read process execution events (execsnoop → perf buffer)
	go func() {
		for {
			// rd.Read() blocks until new event arrives from kernel
			// Returns when: new event ready OR reader closed (shutdown)
			record, err := processRd.Read()
			if err != nil {
				// Error means reader was closed (Ctrl+C pressed)
				// return exits this goroutine
				return
			}

			// Parse raw bytes from kernel into Go struct
			// binary.Read — standard Go library, reads bytes in order
			// bytes.NewReader(record.RawSample) — wrap raw bytes as reader
			// binary.LittleEndian — x86 is little-endian (same as bpfeb/bpfel)
			// &event — pointer to struct to fill
			// Must match EXACT byte layout of C struct in execsnoop.h
			var event ProcessEvent
			if err := binary.Read(
				bytes.NewReader(record.RawSample),
				binary.LittleEndian,
				&event,
			); err != nil {
				log.Printf("parsing process event: %v", err)
				// continue = skip this event, go back to top of for loop
				// Don't crash on bad data — keep monitoring
				continue
			}

			// Convert byte array to string, remove null bytes
			// event.Comm[:] = entire 128-byte array as slice
			// bytes.TrimRight removes trailing \x00 null bytes
			// Without trim: "/usr/bin/curl\x00\x00\x00..." — garbage output
			comm := string(bytes.TrimRight(event.Comm[:], "\x00"))

			container := resolveContainer(event.MntNsId)
			log.Printf("[PROCESS] pid=%-6d ppid=%-6d uid=%-6d mnt_ns=%-10d container=%-40s path=%s",
				event.Pid, event.Ppid, event.Uid, event.MntNsId, container, comm)

			if alert := checkProcessRules(event, container); alert != nil {
				alertHandler.Send(*alert)
			}
		}
	}()

	// Goroutine 2: read process exit events (exitsnoop → ring buffer)
	go func() {
		for {
			// ringbuf.Record slightly different from perf.Record
			// but RawSample works the same way
			record, err := exitRd.Read()
			if err != nil {
				return
			}

			var event ExitEvent
			if err := binary.Read(
				bytes.NewReader(record.RawSample),
				binary.LittleEndian,
				&event,
			); err != nil {
				log.Printf("parsing exit event: %v", err)
				continue
			}

			comm := string(bytes.TrimRight(event.Comm[:], "\x00"))
			durationMs := event.DurationNs / 1_000_000 // convert ns to ms

			log.Printf("[EXIT]    pid=%-6d ppid=%-6d exit_code=%-3d duration=%dms comm=%s",
				event.Pid, event.Ppid, event.ExitCode, durationMs, comm)

			if alert := checkExitRules(event); alert != nil {
				alertHandler.Send(*alert)
			}
		}
	}()

	// Step 7: Block main goroutine until Ctrl+C
	// <-sig reads from channel — blocks until signal received
	// Without this, main() would exit immediately
	// and all goroutines + eBPF programs would be cleaned up
	<-sig
	log.Println("Stopping EDR monitor...")
}