// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcpPiddata struct {
	_    structs.HostLayout
	Comm [16]int8
	Ts   uint64
	Tgid uint32
	_    [4]byte
}

// loadTcp returns the embedded CollectionSpec for tcp.
func loadTcp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcp: %w", err)
	}

	return spec, err
}

// loadTcpObjects loads tcp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcpObjects
//	*tcpPrograms
//	*tcpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpSpecs struct {
	tcpProgramSpecs
	tcpMapSpecs
	tcpVariableSpecs
}

// tcpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpProgramSpecs struct {
	FentryTcpRcvStateProcess *ebpf.ProgramSpec `ebpf:"fentry_tcp_rcv_state_process"`
	FentryTcpV4Connect       *ebpf.ProgramSpec `ebpf:"fentry_tcp_v4_connect"`
	FentryTcpV6Connect       *ebpf.ProgramSpec `ebpf:"fentry_tcp_v6_connect"`
	TcpRcvStateProcess       *ebpf.ProgramSpec `ebpf:"tcp_rcv_state_process"`
	TcpV4Connect             *ebpf.ProgramSpec `ebpf:"tcp_v4_connect"`
	TcpV6Connect             *ebpf.ProgramSpec `ebpf:"tcp_v6_connect"`
}

// tcpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
	Start  *ebpf.MapSpec `ebpf:"start"`
}

// tcpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpVariableSpecs struct {
	TargMinUs *ebpf.VariableSpec `ebpf:"targ_min_us"`
	TargTgid  *ebpf.VariableSpec `ebpf:"targ_tgid"`
}

// tcpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpObjects struct {
	tcpPrograms
	tcpMaps
	tcpVariables
}

func (o *tcpObjects) Close() error {
	return _TcpClose(
		&o.tcpPrograms,
		&o.tcpMaps,
	)
}

// tcpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpMaps struct {
	Events *ebpf.Map `ebpf:"events"`
	Start  *ebpf.Map `ebpf:"start"`
}

func (m *tcpMaps) Close() error {
	return _TcpClose(
		m.Events,
		m.Start,
	)
}

// tcpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpVariables struct {
	TargMinUs *ebpf.Variable `ebpf:"targ_min_us"`
	TargTgid  *ebpf.Variable `ebpf:"targ_tgid"`
}

// tcpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpPrograms struct {
	FentryTcpRcvStateProcess *ebpf.Program `ebpf:"fentry_tcp_rcv_state_process"`
	FentryTcpV4Connect       *ebpf.Program `ebpf:"fentry_tcp_v4_connect"`
	FentryTcpV6Connect       *ebpf.Program `ebpf:"fentry_tcp_v6_connect"`
	TcpRcvStateProcess       *ebpf.Program `ebpf:"tcp_rcv_state_process"`
	TcpV4Connect             *ebpf.Program `ebpf:"tcp_v4_connect"`
	TcpV6Connect             *ebpf.Program `ebpf:"tcp_v6_connect"`
}

func (p *tcpPrograms) Close() error {
	return _TcpClose(
		p.FentryTcpRcvStateProcess,
		p.FentryTcpV4Connect,
		p.FentryTcpV6Connect,
		p.TcpRcvStateProcess,
		p.TcpV4Connect,
		p.TcpV6Connect,
	)
}

func _TcpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcp_x86_bpfel.o
var _TcpBytes []byte
