// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type filePendingOpen struct {
	_        structs.HostLayout
	MntNsId  uint64
	Pid      int32
	Ppid     int32
	Uid      uint32
	Pad      uint32
	Comm     [128]int8
	Filename [256]int8
}

// loadFile returns the embedded CollectionSpec for file.
func loadFile() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FileBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load file: %w", err)
	}

	return spec, err
}

// loadFileObjects loads file and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*fileObjects
//	*filePrograms
//	*fileMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFileObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFile()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// fileSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileSpecs struct {
	fileProgramSpecs
	fileMapSpecs
	fileVariableSpecs
}

// fileProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileProgramSpecs struct {
	HandleEnter *ebpf.ProgramSpec `ebpf:"handle_enter"`
	HandleExit  *ebpf.ProgramSpec `ebpf:"handle_exit"`
}

// fileMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileMapSpecs struct {
	PendingOpens *ebpf.MapSpec `ebpf:"pending_opens"`
	Rb           *ebpf.MapSpec `ebpf:"rb"`
}

// fileVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileVariableSpecs struct {
}

// fileObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileObjects struct {
	filePrograms
	fileMaps
	fileVariables
}

func (o *fileObjects) Close() error {
	return _FileClose(
		&o.filePrograms,
		&o.fileMaps,
	)
}

// fileMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileMaps struct {
	PendingOpens *ebpf.Map `ebpf:"pending_opens"`
	Rb           *ebpf.Map `ebpf:"rb"`
}

func (m *fileMaps) Close() error {
	return _FileClose(
		m.PendingOpens,
		m.Rb,
	)
}

// fileVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileVariables struct {
}

// filePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type filePrograms struct {
	HandleEnter *ebpf.Program `ebpf:"handle_enter"`
	HandleExit  *ebpf.Program `ebpf:"handle_exit"`
}

func (p *filePrograms) Close() error {
	return _FileClose(
		p.HandleEnter,
		p.HandleExit,
	)
}

func _FileClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed file_bpfel.o
var _FileBytes []byte
