// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type FsFileEvent struct {
	_         structs.HostLayout
	MntNsId   uint64
	EventTime uint64
	Pid       int32
	Ppid      int32
	Uid       uint32
	F_mode    uint32
	Ret       int32
	Pad       uint32
	Comm      [16]int8
	Filename  [256]int8
	Cgroup    [128]int8
}

type FsOpenat2Args struct {
	_        structs.HostLayout
	Filename uint64
}

// LoadFs returns the embedded CollectionSpec for Fs.
func LoadFs() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Fs: %w", err)
	}

	return spec, err
}

// LoadFsObjects loads Fs and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*FsObjects
//	*FsPrograms
//	*FsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadFsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadFs()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// FsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FsSpecs struct {
	FsProgramSpecs
	FsMapSpecs
	FsVariableSpecs
}

// FsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FsProgramSpecs struct {
	HandleFileOpen     *ebpf.ProgramSpec `ebpf:"handle_file_open"`
	HandleOpenat2Enter *ebpf.ProgramSpec `ebpf:"handle_openat2_enter"`
	HandleOpenat2Exit  *ebpf.ProgramSpec `ebpf:"handle_openat2_exit"`
}

// FsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FsMapSpecs struct {
	Openat2Pending *ebpf.MapSpec `ebpf:"openat2_pending"`
	Rb             *ebpf.MapSpec `ebpf:"rb"`
}

// FsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FsVariableSpecs struct {
	UnusedExecEvent *ebpf.VariableSpec `ebpf:"__unused_exec_event"`
	UnusedFileEvent *ebpf.VariableSpec `ebpf:"__unused_file_event"`
	UnusedNetEvent  *ebpf.VariableSpec `ebpf:"__unused_net_event"`
}

// FsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadFsObjects or ebpf.CollectionSpec.LoadAndAssign.
type FsObjects struct {
	FsPrograms
	FsMaps
	FsVariables
}

func (o *FsObjects) Close() error {
	return _FsClose(
		&o.FsPrograms,
		&o.FsMaps,
	)
}

// FsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadFsObjects or ebpf.CollectionSpec.LoadAndAssign.
type FsMaps struct {
	Openat2Pending *ebpf.Map `ebpf:"openat2_pending"`
	Rb             *ebpf.Map `ebpf:"rb"`
}

func (m *FsMaps) Close() error {
	return _FsClose(
		m.Openat2Pending,
		m.Rb,
	)
}

// FsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadFsObjects or ebpf.CollectionSpec.LoadAndAssign.
type FsVariables struct {
	UnusedExecEvent *ebpf.Variable `ebpf:"__unused_exec_event"`
	UnusedFileEvent *ebpf.Variable `ebpf:"__unused_file_event"`
	UnusedNetEvent  *ebpf.Variable `ebpf:"__unused_net_event"`
}

// FsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadFsObjects or ebpf.CollectionSpec.LoadAndAssign.
type FsPrograms struct {
	HandleFileOpen     *ebpf.Program `ebpf:"handle_file_open"`
	HandleOpenat2Enter *ebpf.Program `ebpf:"handle_openat2_enter"`
	HandleOpenat2Exit  *ebpf.Program `ebpf:"handle_openat2_exit"`
}

func (p *FsPrograms) Close() error {
	return _FsClose(
		p.HandleFileOpen,
		p.HandleOpenat2Enter,
		p.HandleOpenat2Exit,
	)
}

func _FsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed file_bpfel.o
var _FsBytes []byte
