// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type fileFileEvent struct {
	_         structs.HostLayout
	MntNsId   uint64
	EventTime uint64
	Pid       int32
	Ppid      int32
	Uid       uint32
	F_mode    uint32
	Ret       int32
	Pad       uint32
	Comm      [16]int8
	Filename  [256]int8
	Cgroup    [128]int8
}

type fileOpenat2Args struct {
	_        structs.HostLayout
	Filename uint64
}

// loadFile returns the embedded CollectionSpec for file.
func loadFile() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FileBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load file: %w", err)
	}

	return spec, err
}

// loadFileObjects loads file and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*fileObjects
//	*filePrograms
//	*fileMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFileObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFile()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// fileSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileSpecs struct {
	fileProgramSpecs
	fileMapSpecs
	fileVariableSpecs
}

// fileProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileProgramSpecs struct {
	HandleFileOpen     *ebpf.ProgramSpec `ebpf:"handle_file_open"`
	HandleOpenat2Enter *ebpf.ProgramSpec `ebpf:"handle_openat2_enter"`
	HandleOpenat2Exit  *ebpf.ProgramSpec `ebpf:"handle_openat2_exit"`
}

// fileMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileMapSpecs struct {
	Openat2Pending *ebpf.MapSpec `ebpf:"openat2_pending"`
	Rb             *ebpf.MapSpec `ebpf:"rb"`
}

// fileVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileVariableSpecs struct {
	UnusedExecEvent *ebpf.VariableSpec `ebpf:"__unused_exec_event"`
	UnusedFileEvent *ebpf.VariableSpec `ebpf:"__unused_file_event"`
	UnusedNetEvent  *ebpf.VariableSpec `ebpf:"__unused_net_event"`
}

// fileObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileObjects struct {
	filePrograms
	fileMaps
	fileVariables
}

func (o *fileObjects) Close() error {
	return _FileClose(
		&o.filePrograms,
		&o.fileMaps,
	)
}

// fileMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileMaps struct {
	Openat2Pending *ebpf.Map `ebpf:"openat2_pending"`
	Rb             *ebpf.Map `ebpf:"rb"`
}

func (m *fileMaps) Close() error {
	return _FileClose(
		m.Openat2Pending,
		m.Rb,
	)
}

// fileVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileVariables struct {
	UnusedExecEvent *ebpf.Variable `ebpf:"__unused_exec_event"`
	UnusedFileEvent *ebpf.Variable `ebpf:"__unused_file_event"`
	UnusedNetEvent  *ebpf.Variable `ebpf:"__unused_net_event"`
}

// filePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type filePrograms struct {
	HandleFileOpen     *ebpf.Program `ebpf:"handle_file_open"`
	HandleOpenat2Enter *ebpf.Program `ebpf:"handle_openat2_enter"`
	HandleOpenat2Exit  *ebpf.Program `ebpf:"handle_openat2_exit"`
}

func (p *filePrograms) Close() error {
	return _FileClose(
		p.HandleFileOpen,
		p.HandleOpenat2Enter,
		p.HandleOpenat2Exit,
	)
}

func _FileClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed file_x86_bpfel.o
var _FileBytes []byte
