// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type lsmNetEvent struct {
	_         structs.HostLayout
	MntNsId   uint64
	EventTime uint64
	DstIp     uint32
	DstPort   uint16
	Pad1      uint16
	Pid       int32
	Ppid      int32
	Uid       uint32
	Pad2      uint32
	Comm      [16]int8
}

// loadLsm returns the embedded CollectionSpec for lsm.
func loadLsm() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LsmBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lsm: %w", err)
	}

	return spec, err
}

// loadLsmObjects loads lsm and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lsmObjects
//	*lsmPrograms
//	*lsmMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLsmObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLsm()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lsmSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmSpecs struct {
	lsmProgramSpecs
	lsmMapSpecs
	lsmVariableSpecs
}

// lsmProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmProgramSpecs struct {
	HandleConnect *ebpf.ProgramSpec `ebpf:"handle_connect"`
}

// lsmMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmMapSpecs struct {
	Rb *ebpf.MapSpec `ebpf:"rb"`
}

// lsmVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmVariableSpecs struct {
	UnusedExecEvent *ebpf.VariableSpec `ebpf:"__unused_exec_event"`
	UnusedFileEvent *ebpf.VariableSpec `ebpf:"__unused_file_event"`
	UnusedNetEvent  *ebpf.VariableSpec `ebpf:"__unused_net_event"`
}

// lsmObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmObjects struct {
	lsmPrograms
	lsmMaps
	lsmVariables
}

func (o *lsmObjects) Close() error {
	return _LsmClose(
		&o.lsmPrograms,
		&o.lsmMaps,
	)
}

// lsmMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmMaps struct {
	Rb *ebpf.Map `ebpf:"rb"`
}

func (m *lsmMaps) Close() error {
	return _LsmClose(
		m.Rb,
	)
}

// lsmVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmVariables struct {
	UnusedExecEvent *ebpf.Variable `ebpf:"__unused_exec_event"`
	UnusedFileEvent *ebpf.Variable `ebpf:"__unused_file_event"`
	UnusedNetEvent  *ebpf.Variable `ebpf:"__unused_net_event"`
}

// lsmPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmPrograms struct {
	HandleConnect *ebpf.Program `ebpf:"handle_connect"`
}

func (p *lsmPrograms) Close() error {
	return _LsmClose(
		p.HandleConnect,
	)
}

func _LsmClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lsm_x86_bpfel.o
var _LsmBytes []byte
