// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type SockNetEvent struct {
	_         structs.HostLayout
	MntNsId   uint64
	EventTime uint64
	DstIp     uint32
	DstPort   uint16
	Pad1      uint16
	Pid       int32
	Ppid      int32
	Uid       uint32
	Pad2      uint32
	Comm      [16]int8
}

// LoadSock returns the embedded CollectionSpec for Sock.
func LoadSock() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SockBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Sock: %w", err)
	}

	return spec, err
}

// LoadSockObjects loads Sock and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SockObjects
//	*SockPrograms
//	*SockMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSockObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSock()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SockSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SockSpecs struct {
	SockProgramSpecs
	SockMapSpecs
	SockVariableSpecs
}

// SockProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SockProgramSpecs struct {
	HandleConnect *ebpf.ProgramSpec `ebpf:"handle_connect"`
}

// SockMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SockMapSpecs struct {
	Rb *ebpf.MapSpec `ebpf:"rb"`
}

// SockVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SockVariableSpecs struct {
	UnusedExecEvent *ebpf.VariableSpec `ebpf:"__unused_exec_event"`
	UnusedFileEvent *ebpf.VariableSpec `ebpf:"__unused_file_event"`
	UnusedNetEvent  *ebpf.VariableSpec `ebpf:"__unused_net_event"`
}

// SockObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSockObjects or ebpf.CollectionSpec.LoadAndAssign.
type SockObjects struct {
	SockPrograms
	SockMaps
	SockVariables
}

func (o *SockObjects) Close() error {
	return _SockClose(
		&o.SockPrograms,
		&o.SockMaps,
	)
}

// SockMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSockObjects or ebpf.CollectionSpec.LoadAndAssign.
type SockMaps struct {
	Rb *ebpf.Map `ebpf:"rb"`
}

func (m *SockMaps) Close() error {
	return _SockClose(
		m.Rb,
	)
}

// SockVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadSockObjects or ebpf.CollectionSpec.LoadAndAssign.
type SockVariables struct {
	UnusedExecEvent *ebpf.Variable `ebpf:"__unused_exec_event"`
	UnusedFileEvent *ebpf.Variable `ebpf:"__unused_file_event"`
	UnusedNetEvent  *ebpf.Variable `ebpf:"__unused_net_event"`
}

// SockPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSockObjects or ebpf.CollectionSpec.LoadAndAssign.
type SockPrograms struct {
	HandleConnect *ebpf.Program `ebpf:"handle_connect"`
}

func (p *SockPrograms) Close() error {
	return _SockClose(
		p.HandleConnect,
	)
}

func _SockClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lsm_bpfel.o
var _SockBytes []byte
