// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type processExecEvent struct {
	_         structs.HostLayout
	Pid       int32
	Ppid      int32
	Uid       int32
	MntNsId   uint32
	EventTime uint64
	ExecPath  [256]int8
	Cgroup    [128]int8
	HasTty    uint32
	Args      [128]int8
	Pad       uint32
}

// loadProcess returns the embedded CollectionSpec for process.
func loadProcess() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcessBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load process: %w", err)
	}

	return spec, err
}

// loadProcessObjects loads process and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*processObjects
//	*processPrograms
//	*processMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProcessObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProcess()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// processSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processSpecs struct {
	processProgramSpecs
	processMapSpecs
	processVariableSpecs
}

// processProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processProgramSpecs struct {
	TracepointSyscallsSysEnterExecve *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_execve"`
}

// processMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processMapSpecs struct {
	Events      *ebpf.MapSpec `ebpf:"events"`
	ExecScratch *ebpf.MapSpec `ebpf:"exec_scratch"`
}

// processVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processVariableSpecs struct {
	UnusedExecEvent *ebpf.VariableSpec `ebpf:"__unused_exec_event"`
	UnusedFileEvent *ebpf.VariableSpec `ebpf:"__unused_file_event"`
	UnusedNetEvent  *ebpf.VariableSpec `ebpf:"__unused_net_event"`
}

// processObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processObjects struct {
	processPrograms
	processMaps
	processVariables
}

func (o *processObjects) Close() error {
	return _ProcessClose(
		&o.processPrograms,
		&o.processMaps,
	)
}

// processMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processMaps struct {
	Events      *ebpf.Map `ebpf:"events"`
	ExecScratch *ebpf.Map `ebpf:"exec_scratch"`
}

func (m *processMaps) Close() error {
	return _ProcessClose(
		m.Events,
		m.ExecScratch,
	)
}

// processVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processVariables struct {
	UnusedExecEvent *ebpf.Variable `ebpf:"__unused_exec_event"`
	UnusedFileEvent *ebpf.Variable `ebpf:"__unused_file_event"`
	UnusedNetEvent  *ebpf.Variable `ebpf:"__unused_net_event"`
}

// processPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processPrograms struct {
	TracepointSyscallsSysEnterExecve *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_execve"`
}

func (p *processPrograms) Close() error {
	return _ProcessClose(
		p.TracepointSyscallsSysEnterExecve,
	)
}

func _ProcessClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed process_x86_bpfel.o
var _ProcessBytes []byte
