// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ProcExecEvent struct {
	_         structs.HostLayout
	Pid       int32
	Ppid      int32
	Uid       int32
	MntNsId   uint32
	EventTime uint64
	ExecPath  [256]int8
	Cgroup    [128]int8
	HasTty    uint32
	Args      [128]int8
	Pad       uint32
}

// LoadProc returns the embedded CollectionSpec for Proc.
func LoadProc() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Proc: %w", err)
	}

	return spec, err
}

// LoadProcObjects loads Proc and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ProcObjects
//	*ProcPrograms
//	*ProcMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadProcObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadProc()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ProcSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcSpecs struct {
	ProcProgramSpecs
	ProcMapSpecs
	ProcVariableSpecs
}

// ProcProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcProgramSpecs struct {
	TracepointSyscallsSysEnterExecve *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_execve"`
}

// ProcMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcMapSpecs struct {
	Events      *ebpf.MapSpec `ebpf:"events"`
	ExecScratch *ebpf.MapSpec `ebpf:"exec_scratch"`
}

// ProcVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcVariableSpecs struct {
	UnusedExecEvent *ebpf.VariableSpec `ebpf:"__unused_exec_event"`
	UnusedFileEvent *ebpf.VariableSpec `ebpf:"__unused_file_event"`
	UnusedNetEvent  *ebpf.VariableSpec `ebpf:"__unused_net_event"`
}

// ProcObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadProcObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcObjects struct {
	ProcPrograms
	ProcMaps
	ProcVariables
}

func (o *ProcObjects) Close() error {
	return _ProcClose(
		&o.ProcPrograms,
		&o.ProcMaps,
	)
}

// ProcMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadProcObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcMaps struct {
	Events      *ebpf.Map `ebpf:"events"`
	ExecScratch *ebpf.Map `ebpf:"exec_scratch"`
}

func (m *ProcMaps) Close() error {
	return _ProcClose(
		m.Events,
		m.ExecScratch,
	)
}

// ProcVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadProcObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcVariables struct {
	UnusedExecEvent *ebpf.Variable `ebpf:"__unused_exec_event"`
	UnusedFileEvent *ebpf.Variable `ebpf:"__unused_file_event"`
	UnusedNetEvent  *ebpf.Variable `ebpf:"__unused_net_event"`
}

// ProcPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadProcObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcPrograms struct {
	TracepointSyscallsSysEnterExecve *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_execve"`
}

func (p *ProcPrograms) Close() error {
	return _ProcClose(
		p.TracepointSyscallsSysEnterExecve,
	)
}

func _ProcClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed process_bpfel.o
var _ProcBytes []byte
